apiVersion: batch/v1
kind: CronJob
metadata:
  name: misp-curljob
spec:
  schedule: "* * * * *" # Placeholder; Overridden in overlays
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl-job
              image: curlimages/curl:latest
              command: ["/bin/sh", "-c"]
              args: ["echo 'Placeholder Command'"] # Placeholder; Overridden in overlays
              env:
                - name: BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: misp-cron-secret
                      key: url
                - name: MISP_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: misp-cron-secret
                      key: api_key