apiVersion: v1
kind: Service
metadata:
  name: misp-core
  labels:
    app.kubernetes.io/name: misp-core
    app.kubernetes.io/part-of: misp
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9002
      targetPort: misp-php
      protocol: TCP
      name: misp-php
  selector:
    app.kubernetes.io/name: misp
