apiVersion: batch/v1
kind: CronJob
metadata:
  name: misp-curljob
spec:
  schedule: "20 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-job
            args:
              - >
                curl -sS -X POST "$BASE_URL/noticelists/update"
                -H "Accept: application/json"
                -H "Content-Type: application/json"
                -H "Authorization: $MISP_API_KEY"