include ${NGINX_INCLUDE_DIR}/redirect.conf;

server {
    # general config
    server_name misp;
    root /var/www/MISP/app/webroot;
    error_log /dev/stderr error;
    index index.php;

    # load generated configs (via /docker-entrypoint.d/*.sh) - which could possibly be empty
    include ${NGINX_INCLUDE_DIR}/listen.conf;
    include ${NGINX_INCLUDE_DIR}/ssl.conf;
    include ${NGINX_INCLUDE_DIR}/real-ip.conf;
    include ${NGINX_INCLUDE_DIR}/conditional-headers.conf;

    # configure adjusted mime types
    include /etc/nginx/mime.types;
    types {
        application/javascript mjs;
    }

    # increase the maximum body size
    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};

    # added headers for hardening browser security
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Download-Options "noopen" always;
    add_header X-Frame-Options "${NGINX_X_FRAME_OPTIONS}" always;
    add_header X-Permitted-Cross-Domain-Policies "none" always;
    add_header X-Robots-Tag "none" always;

    # remove X-Powered-By and nginx version, which is an information leak
    fastcgi_hide_header X-Powered-By;
    server_tokens off;

    location ~ /\.(ht|git|env) {
        deny all;
        return 404;
    }

    location ~ ^/[^/]+\.php(/|$) {
        fastcgi_pass ${FASTCGI_LISTEN};
        fastcgi_read_timeout ${FASTCGI_READ_TIMEOUT};
        fastcgi_send_timeout ${FASTCGI_SEND_TIMEOUT};
        fastcgi_connect_timeout ${FASTCGI_CONNECT_TIMEOUT};

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ^~ /css/ {
        try_files $uri =404;
    }

    location ^~ /gpg.asc {
        root /var/www/MISP/cache;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$query_string;
    }
}
