server {
    listen 127.0.0.1:${NGINX_INTERNAL_STATUS_PORT};
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;

    location ^~ /status {
        stub_status;
    }

    location ^~ /fpm-status {
        fastcgi_pass ${FASTCGI_LISTEN_STATUS};
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
