# Use a minimal and secure official NGINX image
FROM nginxinc/nginx-unprivileged:stable-alpine

# Set working directory
WORKDIR /app

# Copy necessary from the local 'files' directory into the container
COPY --chown=101:0 files/etc/nginx/ /etc/nginx/
COPY --chown=101:0 files/var/www/html/ /var/www/html/
COPY --chown=101:0 files/entrypoint_nginx.sh /app/.
COPY --chown=101:0 files/entrypoint_k8s_nginx.sh /app/.

#DEBUG
RUN echo "Listing /app:" && ls -la /app && \
    echo "Listing /etc/nginx:" && ls -la /etc/nginx && \
    echo "Listing /var/www/html:" && ls -la /var/www/html

# Ensure appropriate permissions
RUN chmod -R 755 /etc/nginx /var/www/html /app
# Ensure the entrypoint script is executable
RUN chmod +x /app/entrypoint_k8s_nginx.sh

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint_k8s_nginx.sh"]

# Use a non-root user (already set in nginx-unprivileged image)
USER 101
