apiVersion: v1
kind: Service
metadata:
  name: misp-guard
  labels:
    app.kubernetes.io/name: misp-guard
    app.kubernetes.io/part-of: misp
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: proxy
  selector:
    app.kubernetes.io/name: misp-guard
